name: tripman
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  flutter_bloc: ^8.1.2
  auto_route: ^5.0.4
  equatable: ^2.0.5
  provider: ^6.0.3 
  firebase_core_platform_interface: ^4.5.2
  formz: ^0.4.0
  mask_text_input_formatter: ^2.4.0
  pinput: ^2.2.31
  flutter_svg: ^2.0.3
  multi_image_picker_view: ^0.0.15
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  yandex_geocoder: ^2.1.0
  yandex_mapkit: ^3.2.0
  flutter_map: ^3.1.0
  geocoding: ^2.1.0
  tuple: ^2.0.1
  latlong2: ^0.8.1
  positioned_tap_detector_2: ^1.0.4
  cached_network_image: ^3.2.3
  flutter_image_compress: ^1.1.3

  # proj4dart: ^1.0.4
  # meta: ^1.1.0
  # collection: ^1.14.0



dev_dependencies:
  firebase_auth_platform_interface: ^6.10.4
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: 
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
